-- Rename enum values: CHEF → OPERATOR, COORDINATOR → AGENT
-- PostgreSQL requires ALTER TYPE ... RENAME VALUE (v10+)

ALTER TYPE "UserRole" RENAME VALUE 'CHEF'        TO 'OPERATOR';
ALTER TYPE "UserRole" RENAME VALUE 'COORDINATOR' TO 'AGENT';
